server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /DUTParking

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/DUT_Parking"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  mail:
#    host: localhost
#    port: 3307
#    properties:
#      mail:
#        smtp:
#          auth: false
#          starttls:
#            enable: false
